import AppKit
import Carbon

enum Keyboard {
    /// The virtual key code that types `character` while ⌘ is held in the
    /// current ASCII-capable layout. Fixes ⌘C/⌘V on Dvorak, Colemak, AZERTY…
    static func keyCode(for character: Character, fallback: CGKeyCode) -> CGKeyCode {
        guard let source = TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue(),
              let raw = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return fallback
        }
        let data = Unmanaged<CFData>.fromOpaque(raw).takeUnretainedValue()
        guard let bytes = CFDataGetBytePtr(data) else { return fallback }
        let layout = UnsafeRawPointer(bytes).assumingMemoryBound(to: UCKeyboardLayout.self)
        let target = String(character).lowercased()
        let commandState = UInt32((cmdKey >> 8) & 0xFF)
        for code in 0..<128 {
            var deadKeyState: UInt32 = 0
            var characters = [UniChar](repeating: 0, count: 4)
            var length = 0
            let status = UCKeyTranslate(
                layout,
                UInt16(code),
                UInt16(kUCKeyActionDown),
                commandState,
                UInt32(LMGetKbdType()),
                OptionBits(1 << kUCKeyTranslateNoDeadKeysBit),
                &deadKeyState,
                characters.count,
                &length,
                &characters
            )
            if status == noErr, length > 0,
               String(utf16CodeUnits: characters, count: length).lowercased() == target {
                return CGKeyCode(code)
            }
        }
        return fallback
    }

    /// Waits (up to `timeout`) until no modifier keys are physically held, so a
    /// synthetic ⌘C isn't combined with the ⌃⌥ still held from the shortcut.
    static func waitForModifierRelease(timeout: Duration = .milliseconds(600)) async {
        let modifiers: CGEventFlags = [.maskCommand, .maskAlternate, .maskControl, .maskShift]
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if CGEventSource.flagsState(.combinedSessionState).intersection(modifiers).isEmpty { return }
            try? await Task.sleep(for: .milliseconds(15))
        }
    }

    static func postCommandShortcut(_ character: Character, fallback: CGKeyCode) {
        let key = keyCode(for: character, fallback: fallback)
        let source = CGEventSource(stateID: .privateState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}

enum PasteboardMarker {
    // nspasteboard.org conventions, honored by clipboard managers.
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

/// A copy of the pasteboard's items with their types in original order.
struct ClipboardSnapshot {
    private let items: [[(NSPasteboard.PasteboardType, Data)]]

    init(_ pasteboard: NSPasteboard) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in item.data(forType: type).map { (type, $0) } }
        }
    }

    /// Restores the saved items, marked so clipboard managers don't record
    /// them a second time.
    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let objects = items.map { pairs -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in pairs { item.setData(data, forType: type) }
            return item
        }
        objects.first?.setData(Data(), forType: PasteboardMarker.transient)
        if !objects.isEmpty { pasteboard.writeObjects(objects) }
    }
}

extension NSPasteboard {
    /// Writes text that clipboard managers should ignore.
    func writeTransient(_ text: String) -> Bool {
        clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: PasteboardMarker.transient)
        item.setData(Data(), forType: PasteboardMarker.concealed)
        item.setData(Data(), forType: PasteboardMarker.autoGenerated)
        return writeObjects([item])
    }

    var deniesProgrammaticAccess: Bool {
        if #available(macOS 15.4, *) {
            return accessBehavior == .alwaysDeny
        }
        return false
    }
}
